apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "56.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
  # pull a secret, created by ESO
  valuesFrom:
    - kind: Secret
      name: grafana-admin-credentials
      valuesKey: admin-password
      targetPath: grafana.adminPassword
  values:
    grafana:
      enabled: true
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
